export interface JournalConfig {
  name: string;
  abbreviation: string;
  issn: string;
  eIssn: string | null;
  impactFactor: number | null;
  color: string;
  slug: string;
  pubmedQuery: string;
}

const GI_MESH_FILTER =
  '("Gastroenterology"[MeSH] OR "Gastrointestinal Diseases"[MeSH] OR "Endoscopy, Gastrointestinal"[MeSH] OR "Liver Diseases"[MeSH] OR "Pancreatic Diseases"[MeSH] OR "Inflammatory Bowel Diseases"[MeSH] OR "Gastrointestinal Neoplasms"[MeSH])';

export const JOURNALS: JournalConfig[] = [
  // ── General Medical (GI-filtered) ──────────────────────────────
  {
    name: "The Lancet",
    abbreviation: "Lancet",
    issn: "0140-6736",
    eIssn: "1474-547X",
    impactFactor: 98.4,
    color: "#831843",
    slug: "lancet",
    pubmedQuery: `"Lancet"[ta] AND ${GI_MESH_FILTER}`,
  },
  {
    name: "New England Journal of Medicine",
    abbreviation: "N Engl J Med",
    issn: "0028-4793",
    eIssn: "1533-4406",
    impactFactor: 96.2,
    color: "#7F1D1D",
    slug: "nejm",
    pubmedQuery: `"N Engl J Med"[ta] AND ${GI_MESH_FILTER}`,
  },
  {
    name: "BMJ",
    abbreviation: "BMJ",
    issn: "0959-8138",
    eIssn: "1756-1833",
    impactFactor: 93.6,
    color: "#1E3A5F",
    slug: "bmj",
    pubmedQuery: `"BMJ"[ta] AND ${GI_MESH_FILTER}`,
  },
  {
    name: "JAMA",
    abbreviation: "JAMA",
    issn: "0098-7484",
    eIssn: "1538-3598",
    impactFactor: 63.1,
    color: "#312E81",
    slug: "jama",
    pubmedQuery: `"JAMA"[ta] AND ${GI_MESH_FILTER}`,
  },
  {
    name: "Annals of Internal Medicine",
    abbreviation: "Ann Intern Med",
    issn: "0003-4819",
    eIssn: "1539-3704",
    impactFactor: 39.2,
    color: "#701A75",
    slug: "ann-intern-med",
    pubmedQuery: `"Ann Intern Med"[ta] AND ${GI_MESH_FILTER}`,
  },
  {
    name: "JAMA Network Open",
    abbreviation: "JAMA Netw Open",
    issn: "2574-3805",
    eIssn: null,
    impactFactor: 13.8,
    color: "#4C1D95",
    slug: "jama-network-open",
    pubmedQuery: `"JAMA Netw Open"[ta] AND ${GI_MESH_FILTER}`,
  },

  // ── Tier 1: Top GI/Hepatology ──────────────────────────────────
  {
    name: "Nature Reviews Gastroenterology & Hepatology",
    abbreviation: "Nat Rev Gastroenterol Hepatol",
    issn: "1759-5045",
    eIssn: "1759-5053",
    impactFactor: 45.9,
    color: "#991B1B",
    slug: "nat-rev-gastroenterol-hepatol",
    pubmedQuery: '"Nat Rev Gastroenterol Hepatol"[ta]',
  },
  {
    name: "The Lancet Gastroenterology & Hepatology",
    abbreviation: "Lancet Gastroenterol Hepatol",
    issn: "2468-1253",
    eIssn: "2468-1261",
    impactFactor: 35.7,
    color: "#9F1239",
    slug: "lancet-gastroenterol-hepatol",
    pubmedQuery: '"Lancet Gastroenterol Hepatol"[ta]',
  },
  {
    name: "Gastroenterology",
    abbreviation: "Gastroenterology",
    issn: "0016-5085",
    eIssn: "1528-0012",
    impactFactor: 25.9,
    color: "#DC2626",
    slug: "gastroenterology",
    pubmedQuery: '"Gastroenterology"[ta] AND "0016-5085"[is]',
  },
  {
    name: "Journal of Hepatology",
    abbreviation: "J Hepatol",
    issn: "0168-8278",
    eIssn: "1600-0641",
    impactFactor: 25.7,
    color: "#134E4A",
    slug: "j-hepatol",
    pubmedQuery: '"J Hepatol"[ta]',
  },
  {
    name: "Gut",
    abbreviation: "Gut",
    issn: "0017-5749",
    eIssn: "1468-3288",
    impactFactor: 24.5,
    color: "#1E3A8A",
    slug: "gut",
    pubmedQuery: '"Gut"[ta] AND "0017-5749"[is]',
  },
  {
    name: "Hepatology",
    abbreviation: "Hepatology",
    issn: "0270-9139",
    eIssn: "1527-3350",
    impactFactor: 13.5,
    color: "#065F46",
    slug: "hepatology",
    pubmedQuery: '"Hepatology"[ta] AND "0270-9139"[is]',
  },
  {
    name: "Clinical Endoscopy",
    abbreviation: "Clin Endosc",
    issn: "2234-2400",
    eIssn: "2234-2443",
    impactFactor: 13.3,
    color: "#7C3AED",
    slug: "clinical-endoscopy",
    pubmedQuery: '"Clin Endosc"[ta]',
  },
  {
    name: "Gut and Liver",
    abbreviation: "Gut Liver",
    issn: "1976-2283",
    eIssn: "2005-1212",
    impactFactor: 12.9,
    color: "#0D9488",
    slug: "gut-and-liver",
    pubmedQuery: '"Gut Liver"[ta]',
  },
  {
    name: "Clinical Gastroenterology and Hepatology",
    abbreviation: "Clin Gastroenterol Hepatol",
    issn: "1542-3565",
    eIssn: "1542-7714",
    impactFactor: 11.6,
    color: "#1D4ED8",
    slug: "clin-gastroenterol-hepatol",
    pubmedQuery: '"Clin Gastroenterol Hepatol"[ta]',
  },

  // ── Tier 2: Core GI/Endoscopy ──────────────────────────────────
  {
    name: "The American Journal of Gastroenterology",
    abbreviation: "Am J Gastroenterol",
    issn: "0002-9270",
    eIssn: "1572-0241",
    impactFactor: 9.4,
    color: "#B91C1C",
    slug: "am-j-gastroenterol",
    pubmedQuery: '"Am J Gastroenterol"[ta]',
  },
  {
    name: "Endoscopy",
    abbreviation: "Endoscopy",
    issn: "0013-726X",
    eIssn: "1438-8812",
    impactFactor: 9.3,
    color: "#6D28D9",
    slug: "endoscopy",
    pubmedQuery: '"Endoscopy"[ta] AND "0013-726X"[is]',
  },
  {
    name: "International Journal of Gastrointestinal Intervention",
    abbreviation: "Int J Gastrointest Interv",
    issn: "2636-0004",
    eIssn: null,
    impactFactor: 9.0,
    color: "#2563EB",
    slug: "ijgi",
    pubmedQuery: '"Int J Gastrointest Interv"[ta]',
  },
  {
    name: "Clinical and Molecular Hepatology",
    abbreviation: "Clin Mol Hepatol",
    issn: "2287-2728",
    eIssn: "2287-285X",
    impactFactor: 9.0,
    color: "#166534",
    slug: "clin-mol-hepatol",
    pubmedQuery: '"Clin Mol Hepatol"[ta]',
  },
  {
    name: "Journal of Crohn's and Colitis",
    abbreviation: "J Crohns Colitis",
    issn: "1873-9946",
    eIssn: "1876-4479",
    impactFactor: 8.3,
    color: "#0F766E",
    slug: "j-crohns-colitis",
    pubmedQuery: '"J Crohns Colitis"[ta]',
  },
  {
    name: "Gastrointestinal Endoscopy",
    abbreviation: "Gastrointest Endosc",
    issn: "0016-5107",
    eIssn: "1097-6779",
    impactFactor: 7.7,
    color: "#EA580C",
    slug: "gastrointestinal-endoscopy",
    pubmedQuery: '"Gastrointest Endosc"[ta]',
  },
  {
    name: "Alimentary Pharmacology & Therapeutics",
    abbreviation: "Aliment Pharmacol Ther",
    issn: "0269-2813",
    eIssn: "1365-2036",
    impactFactor: 7.6,
    color: "#1E40AF",
    slug: "aliment-pharmacol-ther",
    pubmedQuery: '"Aliment Pharmacol Ther"[ta]',
  },
  {
    name: "United European Gastroenterology Journal",
    abbreviation: "United European Gastroenterol J",
    issn: "2050-6406",
    eIssn: "2050-6414",
    impactFactor: 5.8,
    color: "#C2410C",
    slug: "ueg-journal",
    pubmedQuery: '"United European Gastroenterol J"[ta]',
  },
  {
    name: "World Journal of Gastroenterology",
    abbreviation: "World J Gastroenterol",
    issn: "1007-9327",
    eIssn: "2219-2840",
    impactFactor: 5.4,
    color: "#059669",
    slug: "world-j-gastroenterol",
    pubmedQuery: '"World J Gastroenterol"[ta]',
  },
  {
    name: "Digestive Endoscopy",
    abbreviation: "Dig Endosc",
    issn: "0915-5635",
    eIssn: "1443-1661",
    impactFactor: 5.0,
    color: "#7E22CE",
    slug: "dig-endosc",
    pubmedQuery: '"Dig Endosc"[ta]',
  },

  // ── Tier 3: Specialty ──────────────────────────────────────────
  {
    name: "Intestinal Research",
    abbreviation: "Intest Res",
    issn: "1598-9100",
    eIssn: "2288-1956",
    impactFactor: 4.7,
    color: "#0E7490",
    slug: "intest-res",
    pubmedQuery: '"Intest Res"[ta]',
  },
  {
    name: "Inflammatory Bowel Diseases",
    abbreviation: "Inflamm Bowel Dis",
    issn: "1078-0998",
    eIssn: "1536-4844",
    impactFactor: 4.5,
    color: "#BE185D",
    slug: "inflamm-bowel-dis",
    pubmedQuery: '"Inflamm Bowel Dis"[ta]',
  },
  {
    name: "Neurogastroenterology and Motility",
    abbreviation: "Neurogastroenterol Motil",
    issn: "1350-1925",
    eIssn: "1365-2982",
    impactFactor: 3.5,
    color: "#A16207",
    slug: "neurogastroenterol-motil",
    pubmedQuery: '"Neurogastroenterol Motil"[ta]',
  },
  {
    name: "Journal of Neurogastroenterology and Motility",
    abbreviation: "J Neurogastroenterol Motil",
    issn: "2093-0879",
    eIssn: "2093-0887",
    impactFactor: 3.5,
    color: "#B45309",
    slug: "j-neurogastroenterol-motil",
    pubmedQuery: '"J Neurogastroenterol Motil"[ta]',
  },
  {
    name: "Journal of Gastrointestinal Surgery",
    abbreviation: "J Gastrointest Surg",
    issn: "1091-255X",
    eIssn: "1873-4626",
    impactFactor: 3.45,
    color: "#D97706",
    slug: "j-gastrointest-surg",
    pubmedQuery: '"J Gastrointest Surg"[ta]',
  },
  {
    name: "Journal of Clinical Gastroenterology",
    abbreviation: "J Clin Gastroenterol",
    issn: "0192-0790",
    eIssn: "1539-2031",
    impactFactor: 3.2,
    color: "#4338CA",
    slug: "j-clin-gastroenterol",
    pubmedQuery: '"J Clin Gastroenterol"[ta]',
  },
  {
    name: "Digestive Diseases and Sciences",
    abbreviation: "Dig Dis Sci",
    issn: "0163-2116",
    eIssn: "1573-2568",
    impactFactor: 3.0,
    color: "#047857",
    slug: "dig-dis-sci",
    pubmedQuery: '"Dig Dis Sci"[ta]',
  },
  {
    name: "Endoscopy International Open",
    abbreviation: "Endosc Int Open",
    issn: "2364-3722",
    eIssn: null,
    impactFactor: 2.5,
    color: "#9333EA",
    slug: "endosc-int-open",
    pubmedQuery: '"Endosc Int Open"[ta]',
  },
  {
    name: "Korean Journal of Internal Medicine",
    abbreviation: "Korean J Intern Med",
    issn: "1226-3303",
    eIssn: "2005-6648",
    impactFactor: 2.4,
    color: "#0369A1",
    slug: "korean-j-intern-med",
    pubmedQuery: '"Korean J Intern Med"[ta]',
  },
  {
    name: "Journal of Gastrointestinal Oncology",
    abbreviation: "J Gastrointest Oncol",
    issn: "2078-6891",
    eIssn: "2219-679X",
    impactFactor: 2.2,
    color: "#E11D48",
    slug: "j-gastrointest-oncol",
    pubmedQuery: '"J Gastrointest Oncol"[ta]',
  },
  {
    name: "VideoGIE",
    abbreviation: "VideoGIE",
    issn: "2468-4481",
    eIssn: null,
    impactFactor: 2.0,
    color: "#DB2777",
    slug: "videogie",
    pubmedQuery: '"VideoGIE"[ta]',
  },
  {
    name: "Korean Journal of Gastroenterology",
    abbreviation: "Korean J Gastroenterol",
    issn: "1598-9992",
    eIssn: "2233-6869",
    impactFactor: 0.7,
    color: "#3730A3",
    slug: "korean-j-gastroenterol",
    pubmedQuery: '"Korean J Gastroenterol"[ta]',
  },
];
